### ISSUE TITLE
Create a func to convert nested dict to nested dataclass

### ISSUE THREAD

**Issue by super56** [fengwj33/playground#1]
We have a dict:
a_dict = {
"jira_id": 1,
"product": [{
  "name": xxx,
  "id": xx
}]

we have nested dataclass:

@dataclass
class Product:
  name: str
  id: str

@dataclass
class JiraProduct:
   jira_id: int
   product: list[Product]

convert to dataclass:
a_cls = JiraProduct(jira_id=1, product=[Product(id=xx, name=xx)])

**Comment by fengwj33** [comment]
https://www.phind.com/search?cache=hadujvpffxisvbk9dg67omfs
